# This is a basic workflow to help you get started with Actions

name: Testing `js-guid`

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Testing with latest version of Node.
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: yarn

      - name: Validating code linting
        run: yarn lint

      - name: Testing using Jest
        run: yarn test
